### ISSUE TITLE
extract timecodes from mkv

### ISSUE THREAD

**Issue by stax76** [stax76/staxrip#118]
https://mkvtoolnix.download/doc/mkvextract.html#mkvextract.description.timecodes_v2

**Comment by JASKevinWhite** [comment]
FYI, you can also add this to FFVideoSource:

FFVideoSource = FFVideoSource("%source_file%", cachefile = "%temp_file%.ffindex", colorspace = "YV12", timecodes="timecodes.txt")

I've done that to my profiles, so at least I get a timecodes.txt file in the StaxRip temp folder.  I then manually re-mux to get the timecodes in to the MKV.

**Comment by stax76** [comment]
I don't know much about the topic, it's needed for source files that have variable frame rate, right?

Maybe you can post a full log file.

**Comment by JASKevinWhite** [comment]
Certainly.  Although I'm not 100% sure I have all of this right either.

The deal is, there are lots of TV shows that were filmed at 23.976, then telecined to 29.97, and then edited.  So some of the file is "progressive", and some of it is just interlaced (of course, it is worse than that: the interlaced parts usually started out as progressive, so the frames contain parts of each).

I'm trying to make .mkv files out of my Star Trek: Deep Space 9 DVDs.  They have this issue.

I was really confused about dealing with this for a long time, because the documentation out there can be confusing.  The most in-depth seems to be:

http://avisynth.nl/index.php/VFR

The problem with that is that the filters used on that page are old and not updated, and are 32-bit only.

So, I wrote a little perl script that does everything that I saw StaxRip do, so that I could experiment with different ways of actually doing this conversion.

It turns out that MakeMKV does a lovely thing.  When it discovers that it is processing a file that is hybrid like this, and (what appears to be a process that is something like ffindex) is able to find a 2:3 cadence (apparently from the MPEG-2 flags, so it appears that the source needs to be soft telecined), it writes out an .mkv file with the timecodes of the frames.  I think this allows smart playback programs to play the 23.976 sections at that frame rate (without judder, if possible), and switch to 29.97 when it needs to.

Doing an encode keeping the frames in this format seems to be a good way to go about it.  It appears to generate playback results about the same quality as just watching the DVD, at least with what I've tested.

I've made a couple of changes to StaxRip's defaults to duplicate what I ended up doing in my script.

- Make "FFVideoSource" in the filters look like:
FFVideoSource = FFVideoSource("%source_file%", cachefile = "%temp_file%.ffindex", colorspace = "YV12", timecodes="%working_dir%timecodes.txt")
- Add "--tff" to the Custom Switches on x264.  I'm not positive this is needed.  I...just can't tell.  Since some of the frames in the input are progressive and some are interlaced, I want the encoding to leave the interlaced fields interlaced.  I'm not sure if there's any difference if I put that option in or not.  What I _hope_ is happening is that that causes the process to do the progressive fields as progressive and the interlaced fields as TFF interlaced.  I determined manually that the interlaced segments for this set of DVDs is TFF.
- Add '--timecodes "%working_dir%timecodes.txt"' to the "Command Line" section of the container.

This results in a .mkv file that has the audio in sync.  If you don't do the timecodes stuff, the audio falls out of sync.

The _problem_ is, the --timecodes option needs to come at the start of the MKV command line, after the -o.  So, this results in an error, because we can't force that in the GUI (that I know of).  Since I ended up doing 7 seasons' worth of this show, I used my Perl script to get everything right.

In other words, StaxRip does this (from the log):

E:\dl\dvdrip\StaxRip\StaxRip-x64-1.4.1.5-test\Apps\MKVToolNix\mkvmerge.exe -o "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_new.mkv" --noaudio --nosubs --no-chapters --no-attachments --no-track-tags --no-global-tags "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue_new_out.h264" --novideo --nosubs --no-chapters --no-attachments --no-track-tags --no-global-tags --audio-tracks 0 --language 0:eng --track-name "0:" --default-track 0:0 "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue ID2 English.ac3" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 0 --forced-track 0:0 --default-track 0:0 --language 0:eng --track-name "0:" "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue ID3 English.idx" --chapters "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue_chapters.xml" --title "Star Trek Deep Space Nine s01e03 Past Prologue" --global-tags "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue_new_tags.xml" --ui-language en --timecodes "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\timecodes.txt"

but it should do this:

E:\dl\dvdrip\StaxRip\StaxRip-x64-1.4.1.5-test\Apps\MKVToolNix\mkvmerge.exe -o "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_new.mkv" --timecodes "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\timecodes.txt" --noaudio --nosubs --no-chapters --no-attachments --no-track-tags --no-global-tags "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue_new_out.h264" --novideo --nosubs --no-chapters --no-attachments --no-track-tags --no-global-tags --audio-tracks 0 --language 0:eng --track-name "0:" --default-track 0:0 "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue ID2 English.ac3" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 0 --forced-track 0:0 --default-track 0:0 --language 0:eng --track-name "0:" "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue ID3 English.idx" --chapters "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue_chapters.xml" --title "Star Trek Deep Space Nine s01e03 Past Prologue" --global-tags "F:\Video\DS9S1D1\done\Star Trek Deep Space Nine s01e03 Past Prologue_temp\Star Trek Deep Space Nine s01e03 Past Prologue_new_tags.xml" --ui-language en

I've attached the log file.  If there's anything else I can provide, I'd love to help.  StaxRip has done a _lot_ of useful work for me over the years.

[Star Trek Deep Space Nine s01e03 Past Prologue_temp.zip](https://github.com/stax76/staxrip/files/925033/Star.Trek.Deep.Space.Nine.s01e03.Past.Prologue_temp.zip)

**Comment by stax76** [comment]
Thanks for the detailed information. I've little experience with NTSC, I've got same samples from users that had problems, unfortunately I always forget after a while most of the things I learned about NTSC processing. 

Things I added for the next build:

- added option to extract timecodes file from MKV (Options > Misc, disabled by default)
- added timecodes file option to muxer dialog, can be TXT or MKV
