### ISSUE TITLE
Crash when trying to enable Crop

### ISSUE THREAD

**Issue by colemar** [stax76/staxrip#126]
Well, this was the first ever encoding job with this StaxRip version.
Granted, the input file was rather big.
Relevant files attached.

[log.zip](https://github.com/stax76/staxrip/files/671977/log.zip)

**Comment by kliffgomel** [comment]
I also have an error and staxrip exception when cropping UHD HEVC video:
AviSynth Error
AviSynth returned empty image data.
[ss_merge_new_StaxRip.log.txt](https://github.com/stax76/staxrip/files/806187/ss_merge_new_StaxRip.log.txt)

**Comment by stax76** [comment]
Does the last test build still cause a problem? I tried a small 4K hevc main10 file which opens fine. I can imagine that with a 70 gb file the source filter will need a huge amount of time to seek and return 20 frames, especially when it's a hdd instead of a ssd.

I measured the crop processing time of StaxRip for 4K files which was 600 ms so any slowness is totally caused by the source filter.

**Comment by kliffgomel** [comment]
In the new version of the program the problem doesn't appear any more.
