### ISSUE TITLE
Use VapourSynth in batch processing

### ISSUE THREAD

**Issue by elahn** [stax76/staxrip#136]
When VapourSynth is installed and AviSynth+ is not installed, File Batch repeatedly displays the window asking to install AviSynth+.

Desired behaviour: use VapourSynth - Automatic

Workaround: add event command `EnsureVapourSynth` for event `After Project Loaded` with no criteria.

**Comment by stax76** [comment]
I think this only happens if your script is AviSynth, you have to change your script to VapourSynth before you open the files:

Filters > Context Menu > Filter Setup > VapourSynth

If you are not using AviSynth you can change all your templates to use VapourSynth.

If AviSynth isn't installed StaxRip makes the guess that he probably wants to install it.
