### ISSUE TITLE
Crash after importing file

### ISSUE THREAD

**Issue by xmaayy** [stax76/staxrip#190]
Your program gave me a log and sent me here after a crash, so hopefully you can tell me what went wrong
```
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                        Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.5.0.0
Windows    : Windows 10 Pro 1703
Language   : English (Canada)
CPU        : Intel(R) Pentium(R) CPU G3220 @ 3.00GHz
GPU        : Intel(R) HD Graphics, NVIDIA GeForce GTX 970
Resolution : 1920 x 1080
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\*****\Desktop\Encoding\Stax\Settings\Scripts\dbUP.vpy

General
Complete name : C:\Users\******\Desktop\Encoding\Stax\Settings\Scripts\dbUP.vpy
File size     : 700 Bytes

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at StaxRip.TaskDialog 1.Show() in D:\Projekte\VS\VB\StaxRip\UI\TaskDialog.vb:line 301
   at StaxRip.MainModule.MsgError(String text, String content) in D:\Projekte\VS\VB\StaxRip\General\General.vb:line 1311
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable 1 files, Boolean isNotEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1741
 
```
and the script that caused it

```
import vapoursynth as vs
core = vs.get_core()

core.std.LoadPlugin(path=r'C:\DankFilters\smash\vslsmashsource.dll')
core.std.LoadPlugin(path=r'C:\DankFilters\fmt\fmtconv.dll')
#core.std.LoadPlugin(path=r'C:\DankFilters\f3kyuu\flash3kyuu_deband.dll')
core.std.LoadPlugin(path=r'C:\DankFilters\Waifu\Waifu2x-caffe.dll')
core.std.LoadPlugin(path=r'C:\DankFilters\BM3D\Win64\BM3D.dll')

clip = core.lsmas.LWLibavSource(source=r'F:\Upscale\RAW\01.mkv')
clip = core.fmtc.bitdepth(clip,bits=32)
#clip = core.f3kdb.Deband(clip, sample_mode=2, dither_algo=3, output_depth=8)
clip = core.caffe.Waifu2x(clip, noise=1, scale=2, block_w=512, block_h=512, model=3, cudnn=True, processor=0, tta=False)

```

**Comment by stax76** [comment]
Hi,

the line that first failed was trying to show a TaskDialog, see:

https://msdn.microsoft.com/en-us/library/windows/desktop/bb760441(v=vs.85).aspx

this task dialog was trying to show an error message returned from VapourSynth so probably there was something wrong with your vpy script. Does this script open in another program, if not does it give a error message? I've tried to import a similar but simplified script:

```
import vapoursynth as vs
core = vs.get_core()

core.std.LoadPlugin(path=r"D:\Projekte\VS\VB\StaxRip\bin\Apps\Plugins\vs\vslsmashsource\vslsmashsource.dll")
clip = core.lsmas.LWLibavSource(source=r"D:\Temp\staxrip\ash.mkv")
clip.set_output()
```

which is working. I received a similar bug report a few years ago but don't remember if it could be solved. I've googled for

TaskDialog UnauthorizedAccessException

and for 

TaskDialog E_ACCESSDENIED

unfortunately I didn't find anything, internally staxrip uses the task TaskDialog API all over the place, even to ask where the settings should be saved on the very first start, old APIs like MessageBox are not used. Since you are a programmer maybe you can try a couple of different things to narrow the problem.

Does TaskDialog now never work and staxrip is totally unusable on your system or does it only not work under certain conditions? You can trigger a task dialog for instance with Tools > Scripts > Re-mux

**Comment by stax76** [comment]
Adding the fmtc line I get:

VFW module doesn't support YUV420PS32 output

**Comment by xmaayy** [comment]
I believe it may actually have been a permissions issue. Just reopening the program without changing any settings or code in that script net me an error in Vapour Synth Compilation, which is to be expected.

 I have no way of accurately reproducing the bug, so that log is all I have. Staxrip is still perfectly usable now. so I dont know if this is a problem that needs fixing or something to hunt down for fun when you have free time.

**Comment by stax76** [comment]
I just hope it don't happen again.
