### ISSUE TITLE
Feature Requests for Job List/Queue

### ISSUE THREAD

**Issue by Fencat** [stax76/staxrip#239]
I frequently have A lot in my queue and sometimes I need to move a job to the top of the queue or do a reboot for various reasons so I have a couple small requests for added usability of the queue.

First one, a move to top of queue button. Currently I have to press the move up button for every step I want to move it up, a move to top would make life easier when you have something you need to get priority. 

Second one, a "When Finished Do" function for current Job in addition to the current when done with queue. Say you need to reboot and have a lot in your queue it would be nice to be able to add a "When done with current job do" a reboot for example.

**Comment by stax76** [comment]
> I frequently have A lot in my queue and sometimes I need to move a job to the top of the queue or do a reboot for various reasons so I have a couple small requests for added usability of the queue.

There will be a menu with shortcut, keeping the shortcut pressed will make it easier to move quickly

> Second one, a "When Finished Do" function for current Job in addition to the current when done with queue. Say you need to reboot and have a lot in your queue it would be nice to be able to add a "When done with current job do" a reboot for example.

I don't like to add something too specialized and in this case it can't easily be added since multiple staxrip instances might work on the job list in parallel, coordinating anything parallel is by nature difficult.

You can achieve your goal with the control's default behavior:

Select the first item and then keep shift pressed and select the last item to do range multi select, then you can press space to check and uncheck the multi selection.

This how the new menu looks:

![unbenannt](https://user-images.githubusercontent.com/11410540/28642414-a5323b9e-7252-11e7-920d-4839c4298488.png)

**Comment by Fencat** [comment]
The menu looks and sounds great! 

And unchecking all with space works well thank you very much, I just couldnt figure out a way to uncheck all but so easy when you know it.... So yea that takes care of my problem thank you.

Please keep up the great work and thank you for looking at my suggestions!

**Comment by stax76** [comment]
You're welcome.
