### ISSUE TITLE
PAR in mp4Box

### ISSUE THREAD

**Issue by JoergWausW** [stax76/staxrip#241]
Issue 2: PAR in mp4Box - it's a minor issue, but interesting...

Part a)
Interesting behavior when picking PAR in MP4->ContainerOptions ->Options->Pixel Aspect Ratio.
The Pulldown Manu offers entries like 12:11 which I chose.
-> The Logfile shows a message "Unrecognized import option 11, ignoring" after ".../Testfile_out.h264#video:par=12:11" in the command line

I tried manually changing ist to 12/11 - the GUI delivers 12:11 to the command line anyway resulting in the same message.
It seems that just 12 or 16 is enogh to have different (and probably correct) settings, see part b)

Part b)
I tried different settings for this PAR option (while not changing the x264 encoder at all, it was set to PAR 12:11)

720x576 and PAR empty -> resulted in an extra line like "Original Display aspect ratio: 4:3" in the log file, must have been included in the muxed file, because opening it in a new instance of StaxRip found the same line in input log.
720x576 and PAR=12:11 -> the extra line is missing, the rest of log file is the same.

VLC player does the same thing for both files anyway:
-> shows DAR=785x576 on screen, that is PAR 12:11, but not DAR 4:3, so this extra line doesn't work in VLC player. What is it for then?

Cropped first:
704x576 and PAR empty -> no extra line in log file
704x576 and PAR 12:11 -> same.
-> VLC shows DAR=768x576 on screen (correct 4:3)

I tried also PAR=16:15 - the option 15 was, again, denied, there were no extra line "Original PAR":
VLC-player is consistent:
720x576 -> DAR=768x576
704x576 -> DAR=750x576

The interesting thing is this extra line in the log file that only appears in one case and doesn't seem to be necessary. If it was, then, for consistency, it should be also inserted into the logfile in the last case (704x576)...

**Comment by stax76** [comment]
Hi, comparing different image specs in the comparison tool isn't yet a supported scenario, I made a separate issue for it:

https://github.com/stax76/staxrip/issues/242

The command line staxrip generates looks OK, the mp4box help says:

> -par trackID=PAR : sets pixel aspect ratio of given track. PAR can be “none” to remove PAR info, or of the form “**N:D**” where N is PAR numerator and D its denominator. Only supported for MPEG-4 Visual and MPEG-4 AVC/H264

I always recommend to output **MKV** and set the PAR in the **encoder** and not the muxer!

Since MKV and mkvmerge are far superior in my opinion I've never provided first class support for mp4box, I can implement and fix things with mp4box but only if people provide guidance and I don't have to do a lot research on my own. mp4box has improved and they are also provide good support. In doubt please ask at doom9 and in the mp4box issue tracker.

https://forum.doom9.org/forumdisplay.php?f=74

https://github.com/gpac/gpac/issues

**Comment by JoergWausW** [comment]
I set the PAR in the encoder (e.g. let it be the way it is).

Could you reproduce the same message about the unrecognized import option? I understand that this is very low on your list of more important things to do. I didn't expect a solution. Shouldn't be your job anyway if the mp4box help describes something the program doesn't recognize...

Anyway - I thought using mp4 is more compatible with TV and DVD-Players... Maybe I should try what my devices do with mkv-files ...

**Comment by stax76** [comment]
I could reproduce it and think it might be a mp4box CLI problem which would not be a surprise because the CLI has known problems, you cannot use the hash character (#) in filenames because it's part of the CLI syntax just like the colon is part of the syntax, there are reasons not to recommend mp4box!

**Comment by JoergWausW** [comment]
Thanks!
