### ISSUE TITLE
NVENC H265 related question

### ISSUE THREAD

**Issue by mrtaichi** [stax76/staxrip#243]
Hello. Consider a Nvidia Pascal/10xx series card. Will it be able to encode in VBR & its HQ (variable bitrate) modes? 

I know the option is there. But some of the options like aq-temporal are not relevant for the H265 encoder. So the confusion. Anyway this question is to help in my purchase decision of a new card. 

Looks the NVENC H265 encoder provides quite a few options. Is the encoding quality of NVENC H265 similar to the software encoder, if the encoding settings are similar?

**Comment by Brainiarc7** [comment]
Hello there, take a look at the [NVIDIA NVENC GPU Support Matrix](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix) and related, [this](https://www.linkedin.com/pulse/nvidias-nvenc-encoder-acceptable-multi-platform-high-hardware-mungai) article for more details.

**Comment by stax76** [comment]
How a hardware encoder compares to a software encoder also depends on bitrate and resolution, some places where you can ask:

https://github.com/rigaya/NVEnc/issues

https://forum.doom9.org/showthread.php?t=174621

**Comment by mrtaichi** [comment]
Thanks guys. Though was there sufficient answer for whether variable bitrate encoding is possible with NVENC H265? I do not think so.

**Comment by Brainiarc7** [comment]
Hello, @mrtaichi ,

To clarify, NVENC, like any other hardware-based encoder, has several limitations, and in particular with HEVC, here are the known limitations:

1. On Pascal:

(a). CTU sizes above 32 are not supported.
(b). B-frames in HEVC are also not supported.
(c). The texture formats supported by the NVENC encoder limit the color spaces that the encoder can work with. For now, we have support for 4:2:0 (8-bit) and 4:4:4 (for 10-bit). Extraneous formats such as 4:2:2 10-bit are not supported. This will affect some workflows where such colorspaces are required. 
(d). Look ahead control is also limited to 32 frames.  You may want to look at [this](https://www.linkedin.com/pulse/nvidias-nvenc-encoder-acceptable-multi-platform-high-hardware-mungai) editorial for more details.

And on Maxwell Gen 2 (GM200x series GPUs):

HEVC encoding lacks the following features:

(a).Sample Adaptive Offset (SAO).
(b).Adaptive quantization
(c). Look-ahead rate control.

The impact here for Maxwell is that motion heavy scenes with HEVC under constrained bitrates may suffer from artifacting (blockiness) due to the missing lookahead functions and adaptive sample offset (SAO) capabilities. Pascal has somewhat improved on this capability, but depending on the version of the SDK that the video encoder was built with, not all features may be available.

For instance, weighted prediction mode for H.264 encodes on Pascal requires NVENC SDK 8.0x and above, and this encode mode will also disable B-frame support. Likewise, the combination of hardware-based scalers running off the [Nvidia Performance Primitives (NPP)](https://developer.nvidia.com/npp) with NVENC may introduce performance improvements with video scaling applications at the cost of scaling artifacting, particularly with upscaled content. The same also impacts the video encode pipeline as NPP's scaling functions run off the CUDA cores on the GPU, and as such, the performance impact introduced by the extra load should be analyzed on a case-by case basis to determine if the performance-quality trade-off is acceptable.

Keep this in mind: A hardware-based encoder will always offer somewhat lesser customization than an equivalent software-based implementation, and as such, your mileage and acceptable output quality will always differ.

**Comment by mrtaichi** [comment]
Thanks Brainiarc7. If I use Avisynth filters in combination with NVENC H265 encoder in staxrip, will those filter processing be done by NVENC or the cpu? Is there a way Avisynth processing can be offset to GPU?

**Comment by Brainiarc7** [comment]
Hello,

For Avisynth, some filters, particularly resize and denoise, can be accelerated via OpenCL on GPUs.
NVENC is a dedicated DSP block for video encoding only.

**Comment by mrtaichi** [comment]
Thanks for the support.

**Comment by stax76** [comment]
Apart from the VPP options there is KNLMeansCL (already in staxrip included) and:

http://rationalqm.us/board/viewforum.php?f=14&sid=dbcdaa4870018023c4711f53f4c71fda
