### ISSUE TITLE
Is there a way to disable .mkv metadata?

### ISSUE THREAD

**Issue by nulledone** [stax76/staxrip#355]
Today I saw that there are lots of information in MKV container's metadata while I was just looking at a file with "MediaInfo". And after a quick look I found mkvpropedit from mkvtoolnix, but I don't want to use it after every encoding.

Further info:

I was trying to delete Writing application and library (successfully done with mkvpropedit).
I just don't want this metadata in my future encodings.
I couldn't find anything releated to writing lib/app in 'Container Options->Tags'

**Comment by jalba69** [comment]
Hello, 

Maybe try this :

- Select MKV for container, then click on " Container Options" 
![2018-01-22_112250](https://user-images.githubusercontent.com/15131985/35216815-38660c9e-ff69-11e7-97ed-6f46b92b7929.png)

- Go to "Command Line" Tab, and click on the small arrow on the right side and "Edit Menu" 
![2018-01-22_112404](https://user-images.githubusercontent.com/15131985/35216870-721dd8ae-ff69-11e7-952d-5e27cbf840bf.png)

- At the top pf the "Menu Editor" past this :
`Remove Date, Tags and Meta = --no-date --disable-track-statistics-tags --engage no_variable_data`

It will then look like this :
![2018-01-22_112507](https://user-images.githubusercontent.com/15131985/35216904-8f5fc58a-ff69-11e7-81d4-4c472db73674.png)

- click OK button to validate and exit the "Menu Editor"

- Now we are back on the "command line" tab: click the small arrow again and select the new menu we created, "Remove Date, Tags and Meta", it will add the command switches we created into the command line window : 
![2018-01-22_115003](https://user-images.githubusercontent.com/15131985/35217195-9fea4faa-ff6a-11e7-9f9e-97556a92a8f8.png)


Do a small encoding or muxing test with mkv container and those switches added using the menu we created and inspect file in mediaifno to see what will remain as metadata when you will create a mkv :)

You can set this to be permament by saving the template once you added the switches or just add the remove metatada switch using the created menu only when you need it :) 

Hope this helps.

**Comment by nulledone** [comment]
Thanks a lot for detailed guide. So, date is now removed but sadly the other lines I mentioned now shows up as following
>Writing library             : no_variable_data
>Writing application         : no_variable_data

When I remove the 'no_variable_data' from bash i get 'Error: '--engage' lacks its argument.'

If it is possible to remove this before encoding I would be much appreciated.

**Comment by jalba69** [comment]
Hi, 

I am not sure if it is possible to remove them directly during the muxing step, the **engage** parameters possible are : 

- space_after_chapters
- no_chapters_in_meta_seek
- no_meta_seek
- lacing_xiph
- lacing_ebml
- native_mpeg4
- no_variable_data
- force_passthrough_packetizer
- write_headers_twice
- allow_avc_in_vfw_mode
- keep_bitstream_ar_info
- no_simpleblocks
- use_codec_state_only
- enable_timestamp_warning
- remove_bitstream_ar_info
- vobsub_subpic_stop_cmds
- no_cue_duration
- no_cue_relative_position
- no_delay_for_garbage_in_avi
- keep_last_chapter_in_mpls
- keep_track_statistics_tags
- all_i_slices_are_key_frames

I guess this will have to be asked to the author of MkvToolNix or maybe requested as an option, or maybe there is a way to do it that i don't know about, for me having it neutral saying "no_variable_data" instead of the usual infos was enough so i never pushed this more.

However it is possible to delete those 2 lines **after the file is created**, i tested quickly in the mkvtoolnix-gui.exe : 

- In the "header editor" , after opening the mkv file, just removing the text like here : 
![2018-01-23_024141](https://user-images.githubusercontent.com/15131985/35253686-0dde1f4c-ffe7-11e7-8298-3367532e6919.gif)

Then going on the top menu > "Header Editor" tab and selecting "Save" and the mkv have those 2 lines removed in mediainfo.

I  don't have time to test this much for now but if it is possible to do this operation only once the file is created then   it is probably possible to create in Staxrip an " Event Command " triggered once the muxing is done to remove those 2 lines in a command line command using mkvtoolnix, need to know the exact command to do this like in the GUI tool tho, will need a bit of digging into the command line tools of MkvToolNix.

I'll try to check in the next coming days and do some tests if i find some free time but no promises, probably the best is to contact directly the MkvToolNix creator to have more infos on all this.

**Comment by jalba69** [comment]
Was fast, I found out the command line to remove them, it's more than 3am here and i'm tired but tomorrow i'll give a try at creating an event command to execute this command on the freshly created MKV at the end of the muxing and post results of tests here.

**Comment by jalba69** [comment]
I left a comment on the latest released version page asking if it is possible achieve this directly during the muxing step: https://www.bunkus.org/blog/2018/01/mkvtoolnix-v20-0-0-released/comment-page-1/#comment-25209
Apparently it isn't possible.

This said I managed to get this working in an automated way using the "event command" function in Staxrip and mkvpropedit.exe
Once the job is done the event command is triggered on the file and command launched to remove those tags using mkvpropedit.exe.

- First i think it's better to create a dedicated template for this, named my dedicated template " **MKV no Metadata** "
- You also need to get **mkvpropedit.exe** ( page in link above ) and place the file somewhere where it can be called easily and repetitively.
I put mine directly inside Staxrip settings folder, inside a sub-folder named "Custom_Tools", since i copy/paste the setting folder to new versions of Staxrip that's the easy way i use to keep the various custom tools used in addition to Staxrip, path is like this  : 
_\StaxRip-x64\Settings\Custom_Tools\Mkvtoolnix\mkvpropedit.exe"_

Having it there will allow me to call it easily in Staxrip with a macro, but it can be placed anywhere and the full path used for the command line too.

Then we need to create the "Event Command" : 
- Go to "Tools" > "Advanced" >  "Event Commands", this will bring the event commands editor
![2018-01-23_135424](https://user-images.githubusercontent.com/15131985/35276942-695c5560-0045-11e8-93b7-7c9d725feaf3.png)

- Set a name for the event command, here i put "mkv remove leftover tags"
- Set the event to be triggered "After Jobs encoded"
- Add criteria  "Muxer Extension" is "mkv"
- Add criteria " Template Name" is "MKV no Metadata" ( Adjust name to your template if you used a different name)
- Select command : on the drop down menu : Execute > ExecuteCommandLine
- Enter the command line to be executed  in the dedicated field ( click on the little button in the right side of the field to bring the editor ).
![2018-01-23_135644](https://user-images.githubusercontent.com/15131985/35277006-9ce1bbf0-0045-11e8-9900-57f0f21e5129.png)

The command line to paste here in this window is   : 

`"%settings_dir%\Custom_Tools\Mkvtoolnix\mkvpropedit.exe" "%target_file%" --set "writing-application=" --set "muxing-application="` 

**( be careful and click on the field and use "paste" from the contextual menu to copy the code above, for some reasons when i tried to use ctrl+v in this field it made Staxrip crash, not sure if it's a bug, i'll have to experiment more with pasting code using ctrl+v i guess )**

The path used to mkvpropedit.exe  is "_%settings_dir%\Custom_Tools\Mkvtoolnix\mkvpropedit.exe"_ for me, using partially a Staxrip marco for the path, but you can set a full path or whatever path to the location where you store your mkvpropedit.exe, like "_H:\somefolder\someotherfolder`\mkvpropedit.exe"_
It's just more easy for me this this way.

Validate all and we are done. 

What this will do is that the next time you use the template named "_MKV no Metadata_" with the output muxed file having the extension "mkv" and the job finished it will execute mkvpropedit.exe on the target file name to remove those two tags using the command we set, all done automatically.

To avoid triggering this when not wanted i think it is better to use a dedicated template like explained earlier, but it's up to you, you can skip this part and not set a criteria for "template name is xx" in case you want this done for all your MKV's 

This seems to work well for me on files i tested so it should do the trick.

PS : I have not tested on a list of many jobs or batched encodes, just with one file to encode, one by one, did not had time to push more testings so no guarantee it works in those cases too, you will have to find out ;)

**Comment by nulledone** [comment]
Thank you a lot for your hard work and research, now I can start encoding without thinking about metadata. Also thanks to stax76 for making such amazing tool.

Also no problems with batch processing, only tried with few same format files. But it seems that there shouldn't be as the 'propedit' command is only dependent on output file.

**Comment by jalba69** [comment]
Nice, 

if you used "After Project processed" in the event command i think batchs or multiple jobs will work yes, if it was "After Jobs encoded" like on my initial thought then only the last video/job on the list will have the tags removed as the command will be triggered only at the end of all jobs and process only the last file i think ^^

Happy to have helped a bit  :)
