### ISSUE TITLE
Support for non-default python installation

### ISSUE THREAD

**Issue by AsukaLangleyfag** [stax76/staxrip#48]
Hello, I have python3 provided by miniconda, but for some reason StaxRip says it's not installed, even if it shows it's version (3.5.1) and if you provide path to python.exe.

**Comment by stax76** [comment]
for python I was using this code:

Registry.CurrentUser.GetString("SOFTWARE\Python\PythonCore\3.5\InstallPath", "ExecutablePath")

Registry.LocalMachine.GetString("SOFTWARE\Python\PythonCore\3.5\InstallPath", "ExecutablePath")

Miniconda creates similar but slightly different reg keys it seems:

Registry.CurrentUser.GetString("SOFTWARE\Python\PythonCore\3.5\InstallPath", nothing).AppendSeparator + "python.exe"

Registry.LocalMachine.GetString("SOFTWARE\Python\PythonCore\3.5\InstallPath", Nothing).AppendSeparator + "python.exe"

I'll upload a new test build shortly.

**Comment by stax76** [comment]
it's currently uploading so will be online shortly

https://github.com/stax76/staxrip/wiki/Test-Build

**Comment by AsukaLangleyfag** [comment]
Honestly, I'd prefer to have an ability to use manual setup, to be able to use with portable python installation.

**Comment by stax76** [comment]
> portable python installation

Doesn't portable mean no installation...

**Comment by AsukaLangleyfag** [comment]
It does, sorry, I was half asleep. Also, i think solution would fix a problem with portable VapourSynth too, as portable VapourSynth Windows installation have this instruction:
>First download and decompress the prerequisites:
        Python 3.5 – 32 or 64 bit embeddable version
Simply decompress the portable VapourSynth archive into the Python dir and overwrite all existing files. Done.
So does the normal installer (https://github.com/vapoursynth/vapoursynth/blob/master/installer/vsinstaller.iss) (it adds vapoursynth.pth with ./vapoursynth folder with vapoursynth.dll and vapoursynth.cp35-win_amd64.pyd inside). I'm not sure if you can create a workaround with PATH variables, but still might be useful. Additionaly you can just provide Python3.5/whatever version of python is used for build with VapourSynth inside. It has all things you need, even VSPipe.exe.

**Comment by stax76** [comment]
Supporting VapourSynth with portable Python I think I would have to replace my VFW interface with a direct interface to VapourSynth, over all it might take 3-4 days so far I'm skeptical if it's worth it.

**Comment by eugenesvk** [comment]
I'd also love to see a portable setup as any deviation is a trouble to work around. For example, VapourSynth doesn't even recognize my conda python either (nor my MSYS2 python for that matter). Portable VapourSynth would work, but then your awesome tool wouldn't.

Totally understand that it might be too much work (is there no simpler way?), but just wanted to +1 to maybe nudge you toward thinking about it :)

**Comment by stax76** [comment]
miniconda should already work in the latest test build, the next build will also search in PATH and Path environment variables, is this sufficient?

**Comment by eugenesvk** [comment]
Given that non-portable VapourSynth requires a classic installation of python (i.e. not conda) as much as I like this step forward, it's doesn't help much practically :(. However, maybe Vapour will update its install routine and allow custom location as well, then it would work)

By the way, if python recognizes a portable VapourSynth module that you can just unpack to any python folder, isn't there a way to make StaxRip utilize this module as well?

**Comment by stax76** [comment]
It's unlikely that I support portable vapoursynth, too much work and piping limitation for not much in return.

**Comment by eugenesvk** [comment]
Would you kindly explain what makes a portable vapoursynth different from installed that breaks StaxRip (mainly out of curiosity since I thought VS was just a python package + some dlls with path written to registry so as long as python is aware of that package it could be via python)?
I'm also curious because maybe there is a simple way to make move an installed version to a conda python by e.g. moving the `site-packages` vapoursynth folder+file and get rid of that extra python that VS needed for the automatic install to work.

**Comment by stax76** [comment]
There is a old vfw interface avisynth and vapoursynth expose, staxrip and virtualdub are the only left apps still using it, it requires system registration. vs portable not only must be supported by the gui but also by all client tools unless, the problem is client tools must support portable too, the encoder might use pipe input but still the tool feeding the pipe must support portable. I don't know if any client tools support portable, vspipe maybe is the only one. It's all very technical and much work, I don't see great benefit in it, switching technology can bring a host of new problems so now I'm not considering to do anything in this direction right, maybe one time when I'm bored but not now. Also don't forget there are much more crappy tools, x265 don't even support avs, let alone vpy. ;-)
